### ISSUE TITLE
publish cookbook to supermarket

### ISSUE THREAD

**Issue by vkhatri** [Icinga/chef-icinga2client#1]
- Upload cookbook to Chef Supermarket
- Make Supermarket User `vkhatri` cookbook collaborator

**Comment by vkhatri** [comment]
@dnsmichi ping!

**Comment by dnsmichi** [comment]
Poke @bobapple please.

**Comment by bobapple** [comment]
@vkhatri I uploaded the cookbook and added you as collaborator
